#!/usr/bin/env python3

import sys

import kconfiglib

if len(sys.argv) != 3:
    sys.exit(f"usage: {sys.argv[0]} .config config.mk")

kconf = kconfiglib.Kconfig("Kconfig")
kconf.load_config(sys.argv[1])

with open(sys.argv[2], "w") as f:
    for sym in kconf.unique_defined_syms:
        if not sym.name:
            continue

        if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
            if sym.str_value in ("y", "m"):
                f.write(f"CONFIG_{sym.name}={sym.str_value}\n")
        elif sym.str_value:
            f.write(f"CONFIG_{sym.name}={sym.str_value}\n")
